# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b4640e29d5eb684c942cfbbadf8111b2d93b48aa7b08783f1de7f97d9692cf7e8a0f5cdfa1a3b27d00e54fcd2621c9e2b2dc861ca49c908ef7eb9a16120724

test:
  secret_key_base: 2e425fc0498beaff7cd25fef359c6ce96d29578a5eff7ed1c105c0d981836736acb1efbbfe7738aacf401a0b92c102bb878a59a6cd981b7de485650597d066bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
